---
    - name: Update packages
      apt:
        name: "*"
        state: latest
        update_cache: yes


  - name: "install node.js "
    become: true
    apt:
      name: ["nodejs"]
      state: latest
      update_cache: yes


    - name: Install npm
      apt:
        name: npm
        state: present
        

  - name: "install pm2 globally"
    npm:
      name: pm2
      global: yes
      
      
  