---
  - name: "add node.js 14 source"
    become: true
    shell:
      curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash 


  - name: "install node.js 14"
    become: true
    apt:
      name: ["nodejs"]
      state: latest
      update_cache: yes


  - name: "install pm2 globally"
    npm:
      name: pm2
      global: yes