
global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'prometheus'

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost: 9093

scrape_configs:
  - job_name: 'prometheus'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters: 
          - name: tag:Project
            values: 
              - Udapeople